#!/bin/bash
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo -e "${GREEN}Maven Core - Local Development Setup${NC}"
echo "======================================="
echo ""

cd "$PROJECT_ROOT"

# Check prerequisites
echo -e "${BLUE}Checking prerequisites...${NC}"

# Check Node.js version
if ! command -v node &> /dev/null; then
  echo -e "${RED}Error: Node.js is not installed${NC}"
  echo "Please install Node.js 20+ from https://nodejs.org/"
  exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
  echo -e "${RED}Error: Node.js 20+ is required (found v$(node -v))${NC}"
  exit 1
fi
echo -e "  ${GREEN}✓${NC} Node.js $(node -v)"

# Check Docker (optional but recommended)
if command -v docker &> /dev/null; then
  echo -e "  ${GREEN}✓${NC} Docker $(docker --version | cut -d' ' -f3 | tr -d ',')"
else
  echo -e "  ${YELLOW}!${NC} Docker not found (optional, needed for agent container)"
fi

# Check Bun (optional, needed for agent development)
if command -v bun &> /dev/null; then
  echo -e "  ${GREEN}✓${NC} Bun $(bun --version)"
else
  echo -e "  ${YELLOW}!${NC} Bun not found (optional, needed for agent development)"
fi

echo ""

# Step 1: Install dependencies
echo -e "${BLUE}[1/5] Installing dependencies...${NC}"
npm install

# Step 2: Build all packages
echo -e "${BLUE}[2/5] Building packages...${NC}"
npm run build

# Step 3: Generate JWT keypair if not exists
echo -e "${BLUE}[3/5] Setting up JWT keys...${NC}"

KEYS_DIR="$PROJECT_ROOT/.keys"
PRIVATE_KEY_FILE="$KEYS_DIR/jwt-private.pem"
PUBLIC_KEY_FILE="$KEYS_DIR/jwt-public.pem"

if [ ! -f "$PRIVATE_KEY_FILE" ] || [ ! -f "$PUBLIC_KEY_FILE" ]; then
  echo "Generating new RS256 keypair (PKCS#8 format)..."
  mkdir -p "$KEYS_DIR"

  # Generate private key in PKCS#8 format (required by jose library)
  openssl genpkey -algorithm RSA -out "$PRIVATE_KEY_FILE" -pkeyopt rsa_keygen_bits:2048 2>/dev/null

  # Extract public key
  openssl pkey -in "$PRIVATE_KEY_FILE" -pubout -out "$PUBLIC_KEY_FILE" 2>/dev/null

  echo -e "${GREEN}Generated new keypair in $KEYS_DIR${NC}"
else
  echo -e "${YELLOW}Using existing keypair in $KEYS_DIR${NC}"
fi

# Read keys (escape newlines for .dev.vars format)
JWT_PRIVATE_KEY=$(cat "$PRIVATE_KEY_FILE")
JWT_PUBLIC_KEY=$(cat "$PUBLIC_KEY_FILE")

# Generate internal API key if not exists
INTERNAL_KEY_FILE="$KEYS_DIR/internal-api-key"
if [ ! -f "$INTERNAL_KEY_FILE" ]; then
  openssl rand -hex 32 > "$INTERNAL_KEY_FILE"
  echo -e "${GREEN}Generated new internal API key${NC}"
fi
INTERNAL_API_KEY=$(cat "$INTERNAL_KEY_FILE")

# Step 4: Create .dev.vars files
echo -e "${BLUE}[4/5] Creating .dev.vars files...${NC}"

# Control Plane .dev.vars
CONTROL_PLANE_VARS="$PROJECT_ROOT/packages/control-plane/.dev.vars"
cat > "$CONTROL_PLANE_VARS" << EOF
# Auto-generated by setup-dev.sh
# Do not commit this file

JWT_PRIVATE_KEY="$JWT_PRIVATE_KEY"

JWT_PUBLIC_KEY="$JWT_PUBLIC_KEY"

INTERNAL_API_KEY="$INTERNAL_API_KEY"
EOF
echo -e "Created ${YELLOW}packages/control-plane/.dev.vars${NC}"

# Tenant Worker .dev.vars
TENANT_WORKER_VARS="$PROJECT_ROOT/packages/tenant-worker/.dev.vars"
cat > "$TENANT_WORKER_VARS" << EOF
# Auto-generated by setup-dev.sh
# Do not commit this file

JWT_PUBLIC_KEY="$JWT_PUBLIC_KEY"

INTERNAL_API_KEY="$INTERNAL_API_KEY"

# Local development URLs
AGENT_URL="http://localhost:8080"
CONTROL_PLANE_URL="http://localhost:8787"

# Optional: Set your Anthropic API key for agent
# ANTHROPIC_API_KEY="your-key-here"

# Optional: Or use AWS Bedrock
# AWS_ACCESS_KEY_ID="your-access-key"
# AWS_SECRET_ACCESS_KEY="your-secret-key"
# AWS_REGION="us-east-1"
EOF
echo -e "Created ${YELLOW}packages/tenant-worker/.dev.vars${NC}"

# Step 5: Run database migrations
echo -e "${BLUE}[5/5] Running database migrations...${NC}"

cd "$PROJECT_ROOT"
./scripts/migrate.sh up

# Done!
echo ""
echo -e "${GREEN}Setup complete!${NC}"
echo ""
echo "To start development servers:"
echo ""
echo -e "  ${YELLOW}npm run dev:start${NC}   - Start all servers in background"
echo -e "  ${YELLOW}npm run dev:status${NC}  - Check server status"
echo -e "  ${YELLOW}npm run dev:logs${NC}    - Tail all logs"
echo -e "  ${YELLOW}npm run dev:stop${NC}    - Stop all servers"
echo ""
echo "Endpoints:"
echo -e "  Control Plane: ${YELLOW}http://localhost:8787${NC}"
echo -e "  Tenant Worker: ${YELLOW}http://localhost:8788${NC}"
echo -e "  Agent:         ${YELLOW}http://localhost:8080${NC}"
echo ""
echo -e "${BLUE}Quick test:${NC}"
echo ""
echo "  # Register a user"
echo '  curl -X POST http://localhost:8787/auth/register \'
echo '    -H "Content-Type: application/json" \'
echo '    -d '\''{"email":"dev@test.com","password":"DevPass123@","name":"Dev User"}'\'''
echo ""
echo "  # Login"
echo '  curl -X POST http://localhost:8787/auth/login \'
echo '    -H "Content-Type: application/json" \'
echo '    -d '\''{"email":"dev@test.com","password":"DevPass123@"}'\'''
echo ""
